# Generated by Django 5.1.6 on 2025-02-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=14)),
                ('descricao', models.CharField(max_length=30)),
                ('nivel', models.CharField(choices=[('B', 'basico'), ('I', 'intermediario'), ('A', 'avançado')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('data_nascimento', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
    ]
